# Включает по умолчанию игрокам функции этого плагина (если игрок уже играл на сервере, то для него изменение этого значения уже не сработает)
crop-replanting-and-harvesting-by-default: true
# Для работы с пересадкой и командами, требуется право ef.replanting
plugin-required-permission: false
# Запрещает с помощью костной муки и правой кнопки мыши бесконечно нажимать на растения
crop-harvesting-prevent-afk-farm: true
# Пересадка растений будет работать только на ЛКМ и при наличии мотыги в руках. Если мотыга не обязательна, то растения пересаживаются на ПКМ с любым предметом.
crop-replant-requires-hoe: false

messages:
  prefix: "#52d447[EasyFarming]#FFFFFF "
  replanting-not-works: Теперь на вас не действует пересаживание растений
  replanting-works: Теперь вы можете пересаживать растения
  no-permission: "#af3e4dУ вас недостаточно прав"
  config-reloaded: Конфиг перезагружен