# Включает по умолчанию игрокам функции этого плагина (если игрок уже играл на сервере, то для него изменение этого значения уже не сработает)
crop-replanting-and-harvesting-by-default: true
# Запрещает с помощью костной муки и правой кнопки мыши бесконечно нажимать на растения
crop-harvesting-prevent-afk-farm: true
# Пересадка растений на ЛКМ, работает только при наличии мотыги в руках.
crop-replant-requires-hoe: false
